# Generated by Django 5.0.6 on 2025-01-07 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkClick',
        ),
    ]
