name: Deploy on AWS

on:
  push:
    branches:
      - main

env:
  openai_api_key: ${{ secrets.OPENAI_API_KEY }}
  assisstant_id: ${{ secrets.ASSISSTANT_ID }}
  db_host: ${{ secrets.DB_HOST }}
  db_port: ${{ secrets.DB_PORT }}
  db_user: ${{ secrets.DB_USER }}
  db_name: ${{ secrets.DB_NAME }}
  db_pwd: ${{ secrets.DB_PWD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build --build-arg secret_key="${{ secrets.SECRET_KEY }}" -t ${{ secrets.DOCKER_USERNAME }}/personal-website:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/personal-website:latest

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.AWS_EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy on AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/personal-website:latest
            docker stop personal-website || true
            docker rm personal-website || true
            docker run -d --name personal-website -p 80:8000 -e secret_key="${{ secrets.SECRET_KEY }}" ${{ secrets.DOCKER_USERNAME }}/personal-website:latest
          EOF
