name: Deploy on AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          run: |
            docker build \
              --build-arg secret_key="${{ secrets.SECRET_KEY }}" \
              --build-arg db_name="${{ secrets.DB_NAME }}" \
              --build-arg db_host="${{ secrets.DB_HOST }}" \
              --build-arg db_port="${{ secrets.DB_PORT }}" \
              --build-arg db_user="${{ secrets.DB_USER }}" \
              --build-arg db_pwd="${{ secrets.DB_PWD }}" \
              --build-arg openai_api_key="${{ secrets.OPENAI_API_KEY }}" \
              --build-arg assisstant_id="${{ secrets.ASSISSTANT_ID }}" \
              -t ${{ secrets.DOCKER_USERNAME }}/personal-website4:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/personal-website4:latest

      - name: Clean up Docker
        run: |
          docker system prune -f

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.AWS_EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy on AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/personal-website4:latest
            docker stop personal-website4 || true
            docker rm personal-website4 || true
            docker run -d --name personal-website4 -p 80:8000 \
              -e secret_key="${{ secrets.SECRET_KEY }}" \
              -e db_name="${{ secrets.DB_NAME }}" \
              -e db_user="${{ secrets.DB_USER }}" \
              -e db_pwd="${{ secrets.DB_PWD }}" \
              -e db_host="${{ secrets.DB_HOST }}" \
              -e db_port="${{ secrets.DB_PORT }}" \
              -e openai_api_key="${{ secrets.OPENAI_API_KEY }}" \
              -e assisstant_id="${{ secrets.ASSISSTANT_ID }}" \
              ${{ secrets.DOCKER_USERNAME }}/personal-website4:latest
          EOF
